previews:
  generation: manual
  expireAfterDays: 1
envVarGroups:
- name: my-env-group
  envVars:
    - key: CONCURRENCY
      value: 2
      previewValue: 8
    - key: SHARED_SECRET
      generateValue: true
services:
- type: web
  autoDeploy: false
  plan: standard
  initialDeployHook: python3 pr_custom_domains.py ${RENDER_SERVICE_SLUG}.mattmaddex.com
  name: simple-sinatra
  env: ruby
  healthCheckPath: /health
  buildCommand: ./build.sh
  startCommand: bundle exec rackup
  preDeployCommand: echo "from pre $RENDER_INSTANCE_ID"

