services:
  - type: web
    autoDeploy: true
    name: custombuild
    env: ruby
    healthCheckPath: /api/utility/health
    rootDir: sin
    branch: mmaddex-custombuild
    envVars:
    - key: PORT
      value: 9292
    - key: test_env
      sync: false
    buildCommand: ./build.sh
    startCommand: ./run.sh
