previewsEnabled: true
services:
  - type: web
    autoDeploy: false
    name: custombuild
    env: ruby
    healthCheckPath: /api/utility/health
    rootDir: sin
    branch: mmaddex-custombuild
    envVars:
    - key: PORT
      value: 9292
    - key: test_env
      sync: false
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 60 # optional if targetCPUPercent is set
      targetCPUPercent: 60 # optional if targetMemory is set
    buildCommand: ./build.sh
    startCommand: ./run.sh
